name: Lint Commit & Codes
on: [pull_request]

jobs:
  commitlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: wagoid/commitlint-github-action@v3

  eslint:
    name: ESLint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Node v15
        uses: actions/setup-node@v2
        with:
          node-version: 15

      - uses: pnpm/action-setup@v2.0.1
        with:
          version: 6.3.0
          run_install: true

      - uses: reviewdog/action-eslint@v1
        with:
          reporter: github-pr-review